### ISSUE TITLE
Select and submit a opinion

### ISSUE THREAD

**Issue by PJDEVEX** [PJDEVEX/love_run#1]
As a **user** I can **select and submit answer from a list** in order to **give my opinion on event and/or location**.

# Acceptance Criteria

1. Five questions to answer on their opinion on event and locations
2. Answers can be picked from a drop down menu
3. Each menu has five options from Dislike to Most preferred

# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include question and dropdown menu
- [ ] Update the controller function
- [ ] Update the unit script function
- [ ] Test the functionality
